services:
  - type: static
    name: pettytradesusu
    repo: https://github.com/ayitteyg/pettytradesusu.git
    branch: main
    buildCommand: npm install && npm run build --configuration production
    publishDir: dist/creditunion/browser
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
